# Generated by Django 5.1.2 on 2024-10-30 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_apirequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiresponse',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='common.apirequest'),
        ),
    ]
